package com.softpath.riverpath.custom.event;

/**
 * A enum to identify the event
 *
 * @author rhajou
 */
public enum EventEnum {
    BOUNDARY_VALIDATED,
    ALLOW_NEW_BOUNDARY_DEF,
    NEW_CONDITION_VALIDATED,
    ALL_CONDITION_VALID,
    INVALID_CONDITION,
    DATA_ENGINEERING_VALID,
    TIME_DISCRETIZATION_VALID,
    RUN_CONFIGURATION_VALID,
    CONVERT_PYTHON_PROCESS_MESSAGE,
    MESHING_PARAMETERS_VALID,
    CIMLIB_PROCESS_END,
    BOUNDARY_NAME_CHANGED,
    BOUNDARY_REMOVED,
    NEW_TOTAL_INCREMENT_VALUE,
    PROGRESS_BAR_UPDATE,
    TITLE_PANE_MODIFIED,
    TITLE_PANE_VALIDATED,
    TITLE_PANE_BOUNDARY_DEF_CREATED
}
